"""increase password_hash length

Revision ID: 1b9f4ef33a79
Revises: 51f5ccfba190
Create Date: 2026-04-02 09:28:07.378867

"""

# revision identifiers, used by Alembic.
revision = '1b9f4ef33a79'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
