"""add avatar filename to users

Revision ID: c687a144b230
Revises: 1b9f4ef33a79
Create Date: 2026-04-02 10:25:23.018830

"""

# revision identifiers, used by Alembic.
revision = 'c687a144b230'
down_revision = '1b9f4ef33a79'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=128), nullable=True))
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'avatar_filename')
    # ### end Alembic commands ###
